steps:
  - name: ':hammer: Build and Unit Test iOS Demo'
    commands:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
    - HOME=$(pwd)
    - source /Users/ec2-user/.rvm/scripts/rvm
    - rvm use ruby-2.7.6
    - bundle install --path vendor/bundle
    - pod install --verbose --allow-root
    - bundle exec fastlane test

    agents:
      queue: 'eng-prod-us-west-2-arm-mac-build-default'