steps:
  - name: ':hammer: Build and Unit Test iOS Demo'
    commands:
    - source /Users/ec2-user/.rvm/scripts/rvm
    - rvm use ruby-2.7.6@ios-demo --create
    - bundle install
    - gem install cocoapods -v 1.11.3
    - echo $HOME

    agents:
      queue: 'eng-prod-us-west-2-arm-mac-build-default'