steps:
  - name: ':hammer: Build and Unit Test iOS Demo'
    commands:
    - chown -R ec2-user *
    - sudo -u ec2-user -s '.buildkite/setup.sh'

    agents:
      queue: 'eng-prod-us-west-2-arm-mac-build-default'