steps:
  - name: ':hammer: Build and Unit Test iOS Demo'
    commands:
    - su ec2-user
    - rvm use ruby-2.7.6@ios-demo --create
    - bundle install
    - pod install --verbose
    - bundle exec fastlane test

    agents:
      queue: 'eng-prod-us-west-2-arm-mac-build-default'