env:
  MAC_BK_AGENT: eng-prod-us-west-2-mac-arm-macos-build-medium

steps:
  - name: ':hammer: Build and Unit Test iOS Demo'
    key: 'unit-test'
    commands:
      - . ~/.zshrc
      - rbenv local 3.2.2
      - bundle install --path vendor/bundle
      - xcrun simctl boot "iPhone 15" || true
      - bundle exec pod install --verbose --repo-update
      - bundle exec fastlane test
      - xcrun simctl shutdown "iPhone 15" || true
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25

  - block: ':whale: Publish to TestFlight'
    key: 'publish-block'
    prompt: 'Confirm publishing to TestFlight?'
    depends_on: 'unit-test'

  - name: ':rocket: Publish demo app to TestFlight'
    commands:
      - . ~/.zshrc
      - rbenv local 3.2.2
      - bundle install --path vendor/bundle
      - bundle exec pod install --verbose --repo-update
      - bundle exec fastlane beta refresh_certificates:false use_temporary_keychain:true
    depends_on: 'publish-block'
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-west-2
          env:
            APPSTORE_KEY_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_KEY_ID'
            APPSTORE_ISSUER_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_ISSUER_ID'
            APPSTORE_KEY_CONTENT_B64:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_KEY_CONTENT_B64'
            MATCH_GIT_URL:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_URL'
            MATCH_GIT_BRANCH:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_BRANCH'
            MATCH_USERNAME:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_USERNAME'
            MATCH_GIT_USER_EMAIL:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_USER_EMAIL'
            MATCH_PASSWORD:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_PASSWORD'
            DEVELOPMENT_TEAM_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.DEVELOPMENT_TEAM_ID'
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25

  - name: ':alarm_clock::rocket: [Scheduled] Publish demo app to TestFlight'
    commands:
      - . ~/.zshrc
      - bundle install --path vendor/bundle
      - bundle exec pod install --verbose --repo-update
      - bundle exec fastlane beta refresh_certificates:false use_temporary_keychain:true
    depends_on: "unit-test"
    if: build.source == "schedule"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-west-2
          env:
            APPSTORE_KEY_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_KEY_ID'
            APPSTORE_ISSUER_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_ISSUER_ID'
            APPSTORE_KEY_CONTENT_B64:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.APPSTORE_KEY_CONTENT_B64'
            MATCH_GIT_URL:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_URL'
            MATCH_GIT_BRANCH:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_BRANCH'
            MATCH_USERNAME:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_USERNAME'
            MATCH_GIT_USER_EMAIL:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_GIT_USER_EMAIL'
            MATCH_PASSWORD:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.MATCH_PASSWORD'
            DEVELOPMENT_TEAM_ID:
              secret-id: 'stage-ios-demoapp-buildkite'
              json-key: '.DEVELOPMENT_TEAM_ID'
    agents:
      queue: ${MAC_BK_AGENT}
    timeout_in_minutes: 25
