name: Build IPA
description: Builds the IPA for the iOS Demo App

inputs:
  certificate_p12_base64:
    description: Base64-encoded p12 signing certificate
    required: true
  certificate_password:
    description: Password for the signing certificate
    required: true
  provisioning_profile_base64:
    description: Base64-encoded provisioning profile
    required: true
  export_options_plist:
    description: Path to ExportOptions.plist
    required: false
    default: ExportOptions.plist

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    
    - name: Setup Xcode
      uses: ./.github/actions/setup-xcode

    - name: Setup keychain and import certificate
      shell: bash
      run: |
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        echo "${{ inputs.certificate_p12_base64 }}" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "${{ inputs.certificate_password }}" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

    - name: Install provisioning profile
      shell: bash
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "${{ inputs.provisioning_profile_base64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

    - name: Archive the app
      shell: bash
      run: |
        xcodebuild -project RoktDemo.xcodeproj \
          -scheme RoktDemo \
          -configuration Release \
          -archivePath build/RoktDemo.xcarchive \
          archive | xcpretty

    - name: Export the app
      shell: bash
      run: |
        xcodebuild -exportArchive \
          -archivePath build/RoktDemo.xcarchive \
          -exportOptionsPlist ${{ inputs.export_options_plist }} \
          -exportPath build | xcpretty

    - name: Upload IPA artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
          name: release-ipa
          path: build/RoktDemo.ipa