name: Pull Request

on:
  push:
    branches:
      - main
      - release/*
      - feature/SQDSDKS-7368-publish-demo-app # TODO:Remove this after testing
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read
  checks: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: macos-latest-xlarge
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2

      - uses: ./.github/actions/setup-environment

      #- uses: ./.github/actions/run-unit-tests

      # TODO: Remove this after testing
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
            app-id: ${{ secrets.SDK_RELEASE_GITHUB_APP_ID }}
            private-key: ${{ secrets.SDK_RELEASE_GITHUB_APP_PRIVATE_KEY }}
            owner: ${{ github.repository_owner }}
            repositories: |
                ios-match-certificates
      - name: Test build IPA
        env:
          DEVELOPMENT_TEAM_ID: ${{ secrets.DEVELOPMENT_TEAM_ID }}
          BUILD_NUMBER: ${{ github.run_number }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_CONTENT_B64: ${{ secrets.APPSTORE_KEY_CONTENT_B64 }}
          MATCH_GIT_URL: https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/ROKT/ios-match-certificates.git
        shell: bash
        run: |
          bundle exec fastlane build_ipa use_temporary_keychain:true refresh_certificates:true
          ls -al
          find . -name "*.ipa"

  pr-notifiy:
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.draft == false
    needs: build
    name: Notify GChat
    uses: ROKT/rokt-workflows/.github/workflows/oss_pr_opened_notification.yml@main
    secrets:
      gchat_webhook: ${{ secrets.GCHAT_PRS_WEBHOOK }}
